force-app/main/default/objects/CustomerDashboard__c/CustomerDashboard__c.object-meta.xml
<CustomObject>
    <label>Customer Dashboard</label>
    <nameField>
        <displayFormat>CD#{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Dashboard</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerDashboard__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Dashboard</relationshipLabel>
    <relationshipName>Customer_Dashboard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseCountDashboardBatchTest.cls
@isTest
private class CaseCountDashboardBatchTest {

    @isTest
    static void testBatchExecution() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        Case cs = new Case(AccountId = testAccount.Id);
        insert cs;
        CustomerDashboard__c customerDashboards = new CustomerDashboard__c(AccountName__c = testAccount.Id);
        insert customerDashboards;
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();
        CaseCountCustomerConnectDashboardBatch batchClass = new CaseCountCustomerConnectDashboardBatch();
        Database.executeBatch(batchClass);
        Test.stopTest();
    }
    
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"data":{"uiapi":{"query":{"Case":{"totalCount":5}}}}}');
            res.setStatusCode(200);
            return res;
        }
    }
}