force-app/main/default/objects/CustomerDashboard__c/CustomerDashboard__c.object-meta.xml
<CustomObject>
    <label>Customer Dashboard</label>
    <nameField>
        <displayFormat>CD#{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Dashboard</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerDashboard__c/fields/ABSLInboundL12M__c.field-meta.xml
<CustomField>
    <fullName>ABSLInboundL12M__c</fullName>
    <label>ABSL Inbound L12M</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/ABSLInboundL3M__c.field-meta.xml
<CustomField>
    <fullName>ABSLInboundL3M__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ABSL Inbound L3M</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/ABSLInboundLM__c.field-meta.xml
<CustomField>
    <fullName>ABSLInboundLM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ABSL Inbound LM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/ABSLInboundMTD__c.field-meta.xml
<CustomField>
    <fullName>ABSLInboundMTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ABSL Inbound MTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/ABSLInboundYTD__c.field-meta.xml
<CustomField>
    <fullName>ABSLInboundYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ABSL Inbound YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/ABSLOutboundL12M__c.field-meta.xml
<CustomField>
    <fullName>ABSLOutboundL12M__c</fullName>
    <label>ABSL Outbound L12M</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/ABSLOutboundL3M__c.field-meta.xml
<CustomField>
    <fullName>ABSLOutboundL3M__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ABSL Outbound L3M</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/ABSLOutboundLM__c.field-meta.xml
<CustomField>
    <fullName>ABSLOutboundLM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ABSL Outbound LM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/ABSLOutboundMTD__c.field-meta.xml
<CustomField>
    <fullName>ABSLOutboundMTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ABSL Outbound MTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/ABSLOutboundYTD__c.field-meta.xml
<CustomField>
    <fullName>ABSLOutboundYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ABSL Outbound YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Dashboard</relationshipLabel>
    <relationshipName>Customer_Dashboard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CollectionL12M__c.field-meta.xml
<CustomField>
    <fullName>CollectionL12M__c</fullName>
    <label>Collection L12M</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CollectionL3M__c.field-meta.xml
<CustomField>
    <fullName>CollectionL3M__c</fullName>
    <label>Collection L3M</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CollectionLM__c.field-meta.xml
<CustomField>
    <fullName>CollectionLM__c</fullName>
    <label>Collection LM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CollectionMTD__c.field-meta.xml
<CustomField>
    <fullName>CollectionMTD__c</fullName>
    <label>Collection MTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CollectionYTD__c.field-meta.xml
<CustomField>
    <fullName>CollectionYTD__c</fullName>
    <label>Collection YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/DIFOTL12M__c.field-meta.xml
<CustomField>
    <fullName>DIFOTL12M__c</fullName>
    <label>DIFOT L12M</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/DIFOTL3M__c.field-meta.xml
<CustomField>
    <fullName>DIFOTL3M__c</fullName>
    <defaultValue>0</defaultValue>
    <label>DIFOT L3M</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/DIFOTLM__c.field-meta.xml
<CustomField>
    <fullName>DIFOTLM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>DIFOT LM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/DIFOTMTD__c.field-meta.xml
<CustomField>
    <fullName>DIFOTMTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>DIFOT MTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/DIFOTYTD__c.field-meta.xml
<CustomField>
    <fullName>DIFOTYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>DIFOT YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/DocketL12M__c.field-meta.xml
<CustomField>
    <fullName>DocketL12M__c</fullName>
    <label>Docket L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/DocketL3M__c.field-meta.xml
<CustomField>
    <fullName>DocketL3M__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Docket L3M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/DocketLM__c.field-meta.xml
<CustomField>
    <fullName>DocketLM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Docket LM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/DocketLMTD__c.field-meta.xml
<CustomField>
    <fullName>DocketLMTD__c</fullName>
    <label>Docket LMTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/DocketMTD__c.field-meta.xml
<CustomField>
    <fullName>DocketMTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Docket MTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/DocketYTD__c.field-meta.xml
<CustomField>
    <fullName>DocketYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Docket YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/MoM__c.field-meta.xml
<CustomField>
    <fullName>MoM__c</fullName>
    <formula>IF( Revenue_LMTD__c =0,0,( RevenueMTD__c - Revenue_LMTD__c  ) / Revenue_LMTD__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MoM%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/OutstandingL12M__c.field-meta.xml
<CustomField>
    <fullName>OutstandingL12M__c</fullName>
    <label>Outstanding L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/OutstandingL3M__c.field-meta.xml
<CustomField>
    <fullName>OutstandingL3M__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outstanding L3M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/OutstandingLM__c.field-meta.xml
<CustomField>
    <fullName>OutstandingLM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outstanding LM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/OutstandingMTD__c.field-meta.xml
<CustomField>
    <fullName>OutstandingMTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outstanding MTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/OutstandingYTD__c.field-meta.xml
<CustomField>
    <fullName>OutstandingYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outstanding YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/Revenue_LMTD__c.field-meta.xml
<CustomField>
    <fullName>Revenue_LMTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revenue LMTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/RevenueL12M__c.field-meta.xml
<CustomField>
    <fullName>RevenueL12M__c</fullName>
    <label>Revenue L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/RevenueL3M__c.field-meta.xml
<CustomField>
    <fullName>RevenueL3M__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revenue L3M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/RevenueLM__c.field-meta.xml
<CustomField>
    <fullName>RevenueLM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revenue LM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/RevenueMTD__c.field-meta.xml
<CustomField>
    <fullName>RevenueMTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revenue MTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/RevenueYTD__c.field-meta.xml
<CustomField>
    <fullName>RevenueYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revenue YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VisitsL12M__c.field-meta.xml
<CustomField>
    <fullName>VisitsL12M__c</fullName>
    <label># Visits L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VisitsL3M__c.field-meta.xml
<CustomField>
    <fullName>VisitsL3M__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Visits L3M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VisitsLM__c.field-meta.xml
<CustomField>
    <fullName>VisitsLM__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Visits LM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VisitsLMTD__c.field-meta.xml
<CustomField>
    <fullName>VisitsLMTD__c</fullName>
    <label># Visits LMTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VisitsMTD__c.field-meta.xml
<CustomField>
    <fullName>VisitsMTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Visits MTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VisitsYTD__c.field-meta.xml
<CustomField>
    <fullName>VisitsYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Visits YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VolumeL12M__c.field-meta.xml
<CustomField>
    <fullName>VolumeL12M__c</fullName>
    <label>Volume L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VolumeL3M__c.field-meta.xml
<CustomField>
    <fullName>VolumeL3M__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Volume L3M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VolumeLM__c.field-meta.xml
<CustomField>
    <fullName>VolumeLM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Volume LM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VolumeLMTD__c.field-meta.xml
<CustomField>
    <fullName>VolumeLMTD__c</fullName>
    <label>Volume LMTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VolumeMTD__c.field-meta.xml
<CustomField>
    <fullName>VolumeMTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Volume MTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/VolumeYTD__c.field-meta.xml
<CustomField>
    <fullName>VolumeYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Volume YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomerDashboardCalculationsBatch.cls
public class CustomerDashboardCalculationsBatch implements Database.Batchable<sObject>, Database.Stateful {
    public Date StartDate;
    public Date EndDate;
    public String Identifier;
    public String currentMonthYear;
    
    public CustomerDashboardCalculationsBatch(Date StartDate, Date EndDate, String Identifier){
        this.StartDate = StartDate;
        this.EndDate = EndDate;
        this.Identifier = Identifier;
        if(Identifier == 'MTD'){
            this.currentMonthYear = IncentiveUtility.getMonthName(StartDate.month())+'-'+StartDate.year();
        }
        else{
            this.currentMonthYear = IncentiveUtility.getMonthName(System.today().month())+'-'+System.today().year();
        }
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query =	'SELECT Id,AccountName__c,ABSLInboundL12M__c,ABSLOutboundL12M__c,DIFOTL12M__c,DocketL12M__c,OutstandingL12M__c,RevenueL12M__c,VisitsL12M__c,VolumeL12M__c,ABSLInboundL3M__c,ABSLOutboundL3M__c,DIFOTL3M__c,DocketL3M__c,OutstandingL3M__c,RevenueL3M__c,VisitsL3M__c,VolumeL3M__c,ABSLInboundLM__c,ABSLOutboundLM__c,DIFOTLM__c,DocketLM__c,OutstandingLM__c,RevenueLM__c,VisitsLM__c,VolumeLM__c,ABSLInboundMTD__c,ABSLOutboundMTD__c,DIFOTMTD__c,DocketMTD__c,OutstandingMTD__c,RevenueMTD__c,VisitsMTD__c,VolumeMTD__c,ABSLInboundYTD__c,ABSLOutboundYTD__c,DIFOTYTD__c,DocketYTD__c,OutstandingYTD__c,RevenueYTD__c,VisitsYTD__c,VolumeYTD__c,CollectionMTD__c,CollectionLM__c,CollectionL3M__c,CollectionL12M__c,CollectionYTD__c,VisitsLMTD__c,On_time_arrival_Dockets_MTD__c, On_Time_Delivered_With_Out_Deps_MTD__c, Total_Assured_Dockets_MTD__c FROM CustomerDashboard__c';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<CustomerDashboard__c> scope){
        Set<Id> accIds = new Set<Id>();
        Map<Id,Integer> accIdToVisitCount = new Map<Id,Integer>();
        //Map<Id,Decimal> accIdToOutbound = new Map<Id,Decimal>();
        Map<Id,Decimal> accIdToDocketNumber = new Map<Id,Decimal>();
        Map<Id,Decimal> accIdToOutstanding = new Map<Id,Decimal>();
        Map<Id,Decimal> accIdToRevenue = new Map<Id,Decimal>();
        Map<Id,Decimal> accIdToVolume = new Map<Id,Decimal>();
        Map<Id,Decimal> accIdToCollection = new Map<Id,Decimal>();
        Map<Id,Decimal> accIdToRevenueLMTD = new Map<Id,Decimal>();
        Map<Id,Decimal> accIdToDocketLMTD = new Map<Id,Decimal>();
        Map<Id,Decimal> accIdToVolumnLMTD = new Map<Id,Decimal>();
        //Added for Difot And ABSL
        Map<Id,Decimal> accIdToTotalAssured = new Map<Id,Decimal>();
        Map<Id,Decimal> accIdToOnTimeDelivered = new Map<Id,Decimal>();
        Map<Id,Decimal> accIdToOnTimeArrival = new Map<Id,Decimal>();
        List<CustomerDashboard__c> dashboardListToUpdate = new List<CustomerDashboard__c>();
        List<MonthlyTradeDashboard__c> monthlyTradesToUpdate = new List<MonthlyTradeDashboard__c>();
        
        for(CustomerDashboard__c cd : scope){
            accIds.add(cd.AccountName__c);
        }

        List<MonthlyTradeDashboard__c> monthlyTrades = [SELECT Id, Name, ContractName__c, RevenueMTD__c, RevenueLMTD__c, RevenueYTD__c, 
                                                        UpDownTrade__c, MoM__c, MonthYear__c
                                                        FROM MonthlyTradeDashboard__c
                                                        WHERE MonthYear__c = :currentMonthYear
                                                        AND ContractName__c IN :accIds
                                                       ];        
        List<Customer360__c> customer360List = [SELECT Customer_Code__c,Customer_Code__r.ParentId,No_of_dkt_MTD__c,LM_TD__c,
                                                Ch_wt_MTD__c,MTD__c,DIFOT__c,ABSL_Inbound__c,ABSL_Outbound__c,Current_Month_OS__c,
                                                COLL_as_on_date__c,CYLM_No_of_Dockets__c,CYLM_Charged_Wt__c,Total_Assured_Dockets__c,
                                                ON_time_delivered_with_out_deps__c,On_time_arrival_Dockets__c  
                                                FROM Customer360__c 
                                                WHERE As_on_date__c >=: StartDate
                                                AND As_on_date__c <=: EndDate
                                                AND (Customer_Code__c IN: accIds OR Customer_Code__r.ParentId IN: accIds)
                                               ];
        List<Customer_Connect__c> customerConnectList = [SELECT Id, Customer_Code__c,Customer_Code__r.ParentId
                                                         FROM Customer_Connect__c
                                                         WHERE (Customer_Code__c IN: accIds OR Customer_Code__r.ParentId IN: accIds)
                                                         AND Visit_Date__c >=: StartDate
                                                         AND Visit_Date__c <=: EndDate
                                                        ];
        
        if(customer360List != null && customer360List.size()>0){
            for(Customer360__c cm : customer360List){
                Id key = null;
                if(cm.Customer_Code__r.ParentId != null){
                    key = cm.Customer_Code__r.ParentId;
                }
                else{
                    key = cm.Customer_Code__c;
                }
                
                /*if(cm.ABSL_Outbound__c != null){
                    if(accIdToOutbound.containsKey(key)){
                        if(accIdToOutbound.get(key) < cm.ABSL_Outbound__c){
                            accIdToOutbound.put(key,cm.ABSL_Outbound__c);   
                        }
                    }
                    else{
                        accIdToOutbound.put(key,cm.ABSL_Outbound__c);
                    } 
                }*/
                //Added for Difot And ABSL MTD
                if(cm.Total_Assured_Dockets__c != null){
                    if(accIdToTotalAssured.containsKey(key)){
                        accIdToTotalAssured.put(key,(accIdToTotalAssured.get(key)+cm.Total_Assured_Dockets__c));
                    }
                    else{
                        accIdToTotalAssured.put(key,cm.Total_Assured_Dockets__c);
                    }   
                }
                
                if(cm.On_time_arrival_Dockets__c != null){
                    if(accIdToOnTimeArrival.containsKey(key)){
                        accIdToOnTimeArrival.put(key,(accIdToOnTimeArrival.get(key)+cm.On_time_arrival_Dockets__c));
                    }
                    else{
                        accIdToOnTimeArrival.put(key,cm.On_time_arrival_Dockets__c);
                    }   
                }
                
                if(cm.ON_time_delivered_with_out_deps__c != null){
                    if(accIdToOnTimeDelivered.containsKey(key)){
                        accIdToOnTimeDelivered.put(key,(accIdToOnTimeDelivered.get(key)+cm.ON_time_delivered_with_out_deps__c));
                    }
                    else{
                        accIdToOnTimeDelivered.put(key,cm.ON_time_delivered_with_out_deps__c);
                    }   
                }
                
                if(accIdToDocketNumber.containsKey(key)){
                    accIdToDocketNumber.put(key,(accIdToDocketNumber.get(key)+cm.No_of_dkt_MTD__c));
                }
                else{
                    accIdToDocketNumber.put(key,cm.No_of_dkt_MTD__c);
                }
                if(accIdToOutstanding.containsKey(key)){
                    accIdToOutstanding.put(key,(accIdToOutstanding.get(key)+cm.Current_Month_OS__c));
                }
                else{
                    accIdToOutstanding.put(key,cm.Current_Month_OS__c);
                }
                if(accIdToRevenue.containsKey(key)){
                    accIdToRevenue.put(key,(accIdToRevenue.get(key)+cm.MTD__c));
                }
                else{
                    accIdToRevenue.put(key,cm.MTD__c);
                }
                if(accIdToVolume.containsKey(key)){
                    accIdToVolume.put(key,(accIdToVolume.get(key)+cm.Ch_wt_MTD__c));
                }
                else{
                    accIdToVolume.put(key,cm.Ch_wt_MTD__c);
                }
                if(accIdToRevenueLMTD.containsKey(key)){
                    accIdToRevenueLMTD.put(key,(accIdToRevenueLMTD.get(key)+cm.LM_TD__c));
                }
                else{
                    accIdToRevenueLMTD.put(key,cm.LM_TD__c);
                }
                if(cm.CYLM_Charged_Wt__c != null){
                    if(accIdToVolumnLMTD.containsKey(key)){
                        accIdToVolumnLMTD.put(key,(accIdToVolumnLMTD.get(key)+cm.CYLM_Charged_Wt__c));
                    }
                    else{
                        accIdToVolumnLMTD.put(key,cm.CYLM_Charged_Wt__c);
                    }
                }
                if(cm.CYLM_No_of_Dockets__c != null){
                    if(accIdToDocketLMTD.containsKey(key)){
                        accIdToDocketLMTD.put(key,(accIdToDocketLMTD.get(key)+cm.CYLM_No_of_Dockets__c));
                    }
                    else{
                        accIdToDocketLMTD.put(key,cm.CYLM_No_of_Dockets__c);
                    }
                }
                if(accIdToCollection.containsKey(key)){
                    accIdToCollection.put(key,(accIdToCollection.get(key)+cm.COLL_as_on_date__c));
                }
                else{
                    accIdToCollection.put(key,cm.COLL_as_on_date__c);
                }
            }
        }
        if(customerConnectList != null && customerConnectList.size()>0){
            for(Customer_Connect__c cc : customerConnectList){
                Id key = null;
                if(cc.Customer_Code__r.ParentId != null){
                    key = cc.Customer_Code__r.ParentId;
                }
                else{
                    key = cc.Customer_Code__c;
                }
                
                if(accIdToVisitCount.containsKey(key)){
                    accIdToVisitCount.put(key,(accIdToVisitCount.get(key)+1));
                }
                else{
                    accIdToVisitCount.put(key,1);
                }
            }
        }
        
        for(CustomerDashboard__c cdash : scope){
            if(Identifier == 'L12M'){
                cdash.VisitsL12M__c = accIdToVisitCount.containsKey(cdash.AccountName__c) ? accIdToVisitCount.get(cdash.AccountName__c) : 0;
                cdash.DocketL12M__c = accIdToDocketNumber.containsKey(cdash.AccountName__c) ? (accIdToDocketNumber.get(cdash.AccountName__c)) : 0;
                cdash.OutstandingL12M__c = accIdToOutstanding.containsKey(cdash.AccountName__c) ? (accIdToOutstanding.get(cdash.AccountName__c)) : 0;
                cdash.RevenueL12M__c = accIdToRevenue.containsKey(cdash.AccountName__c) ? (accIdToRevenue.get(cdash.AccountName__c)) : 0;
                cdash.VolumeL12M__c = accIdToVolume.containsKey(cdash.AccountName__c) ? (accIdToVolume.get(cdash.AccountName__c)) : 0;
            }
            else if(Identifier == 'L3M'){
                cdash.VisitsL3M__c = accIdToVisitCount.containsKey(cdash.AccountName__c) ? accIdToVisitCount.get(cdash.AccountName__c) : 0;
                cdash.DocketL3M__c = accIdToDocketNumber.containsKey(cdash.AccountName__c) ? (accIdToDocketNumber.get(cdash.AccountName__c)) : 0;
                cdash.OutstandingL3M__c = accIdToOutstanding.containsKey(cdash.AccountName__c) ? (accIdToOutstanding.get(cdash.AccountName__c)) : 0;
                cdash.RevenueL3M__c = accIdToRevenue.containsKey(cdash.AccountName__c) ? (accIdToRevenue.get(cdash.AccountName__c)) : 0;
                cdash.VolumeL3M__c = accIdToVolume.containsKey(cdash.AccountName__c) ? (accIdToVolume.get(cdash.AccountName__c)) : 0;
            }
            else if(Identifier == 'LM'){
                cdash.VisitsLM__c = accIdToVisitCount.containsKey(cdash.AccountName__c) ? accIdToVisitCount.get(cdash.AccountName__c) : 0;
                cdash.DocketLM__c = accIdToDocketNumber.containsKey(cdash.AccountName__c) ? (accIdToDocketNumber.get(cdash.AccountName__c)) : 0;
                cdash.OutstandingLM__c = accIdToOutstanding.containsKey(cdash.AccountName__c) ? (accIdToOutstanding.get(cdash.AccountName__c)) : 0;
                cdash.RevenueLM__c = accIdToRevenue.containsKey(cdash.AccountName__c) ? (accIdToRevenue.get(cdash.AccountName__c)) : 0;
                cdash.VolumeLM__c = accIdToVolume.containsKey(cdash.AccountName__c) ? (accIdToVolume.get(cdash.AccountName__c)) : 0;
            }
            else if(Identifier == 'MTD'){
                cdash.VisitsMTD__c = accIdToVisitCount.containsKey(cdash.AccountName__c) ? accIdToVisitCount.get(cdash.AccountName__c) : 0;
                //cdash.ABSLOutboundMTD__c = accIdToOutbound.containsKey(cdash.AccountName__c) ? accIdToOutbound.get(cdash.AccountName__c) : 0;
                cdash.DocketMTD__c = accIdToDocketNumber.containsKey(cdash.AccountName__c) ? (accIdToDocketNumber.get(cdash.AccountName__c)) : 0;
                cdash.OutstandingMTD__c = accIdToOutstanding.containsKey(cdash.AccountName__c) ? (accIdToOutstanding.get(cdash.AccountName__c)) : 0;
                cdash.RevenueMTD__c = accIdToRevenue.containsKey(cdash.AccountName__c) ? (accIdToRevenue.get(cdash.AccountName__c)) : 0;
                cdash.VolumeMTD__c = accIdToVolume.containsKey(cdash.AccountName__c) ? (accIdToVolume.get(cdash.AccountName__c)) : 0;
				cdash.Revenue_LMTD__c = accIdToRevenueLMTD.containsKey(cdash.AccountName__c) ? (accIdToRevenueLMTD.get(cdash.AccountName__c)) : 0; 
                cdash.CollectionMTD__c = accIdToCollection.containsKey(cdash.AccountName__c) ? (accIdToCollection.get(cdash.AccountName__c)) : 0;
                cdash.VolumeLMTD__c = accIdToVolumnLMTD.containsKey(cdash.AccountName__c) ? (accIdToVolumnLMTD.get(cdash.AccountName__c)) : 0;
                cdash.DocketLMTD__c = accIdToDocketLMTD.containsKey(cdash.AccountName__c) ? (accIdToDocketLMTD.get(cdash.AccountName__c)) : 0;
                //Added for Difot And ABSL
                cdash.On_time_arrival_Dockets_MTD__c = accIdToOnTimeArrival.containsKey(cdash.AccountName__c) ? (accIdToOnTimeArrival.get(cdash.AccountName__c)) : 0;
                cdash.Total_Assured_Dockets_MTD__c = accIdToTotalAssured.containsKey(cdash.AccountName__c) ? (accIdToTotalAssured.get(cdash.AccountName__c)) : 0;
                cdash.On_Time_Delivered_With_Out_Deps_MTD__c = accIdToOnTimeDelivered.containsKey(cdash.AccountName__c) ? (accIdToOnTimeDelivered.get(cdash.AccountName__c)) : 0;
                if(accIdToTotalAssured.containsKey(cdash.AccountName__c) && accIdToOnTimeDelivered.containsKey(cdash.AccountName__c) && accIdToTotalAssured.get(cdash.AccountName__c) != 0){
                    cdash.DIFOTMTD__c = ((accIdToOnTimeDelivered.get(cdash.AccountName__c)) / (accIdToTotalAssured.get(cdash.AccountName__c)))*100;
                }
                else{
                    cdash.DIFOTMTD__c = 0;
                }
                
                if(accIdToTotalAssured.containsKey(cdash.AccountName__c) && accIdToOnTimeArrival.containsKey(cdash.AccountName__c) && accIdToTotalAssured.get(cdash.AccountName__c) != 0){
                    cdash.ABSLInboundMTD__c = ((accIdToOnTimeArrival.get(cdash.AccountName__c)) / (accIdToTotalAssured.get(cdash.AccountName__c)))*100;
                }
                else{
                    cdash.ABSLInboundMTD__c = 0;
                }
            }
            else if(Identifier == 'YTD'){
                cdash.VisitsYTD__c = accIdToVisitCount.containsKey(cdash.AccountName__c) ? accIdToVisitCount.get(cdash.AccountName__c) : 0;
                cdash.DocketYTD__c = accIdToDocketNumber.containsKey(cdash.AccountName__c) ? (accIdToDocketNumber.get(cdash.AccountName__c)) : 0;
                cdash.OutstandingYTD__c = accIdToOutstanding.containsKey(cdash.AccountName__c) ? (accIdToOutstanding.get(cdash.AccountName__c)) : 0;
                cdash.RevenueYTD__c = accIdToRevenue.containsKey(cdash.AccountName__c) ? (accIdToRevenue.get(cdash.AccountName__c)) : 0;
                cdash.VolumeYTD__c = accIdToVolume.containsKey(cdash.AccountName__c) ? (accIdToVolume.get(cdash.AccountName__c)) : 0;
            }
            else if(Identifier == 'LMTD'){
                cdash.VisitsLMTD__c = accIdToVisitCount.containsKey(cdash.AccountName__c) ? accIdToVisitCount.get(cdash.AccountName__c) : 0;
            }
            dashboardListToUpdate.add(cdash);
        }
        for(MonthlyTradeDashboard__c mTrade : monthlyTrades){
            if(Identifier == 'MTD'){
                mTrade.RevenueMTD__c = accIdToRevenue.containsKey(mTrade.ContractName__c) ? (accIdToRevenue.get(mTrade.ContractName__c)) : 0;
                mTrade.RevenueLMTD__c = accIdToRevenueLMTD.containsKey(mTrade.ContractName__c) ? (accIdToRevenueLMTD.get(mTrade.ContractName__c)) : 0;
            }
            else if(Identifier == 'YTD'){
                mTrade.RevenueYTD__c = accIdToRevenue.containsKey(mTrade.ContractName__c) ? (accIdToRevenue.get(mTrade.ContractName__c)) : 0;
            }
            monthlyTradesToUpdate.add(mTrade);
        }
        
        if(dashboardListToUpdate != null && dashboardListToUpdate.size()>0){
            update dashboardListToUpdate;
        }
        if(monthlyTradesToUpdate != null && monthlyTradesToUpdate.size()>0){
            update monthlyTradesToUpdate;
        }
    }
    public void finish(Database.BatchableContext BC){
        Date sDate = null;
        Date eDate = null;
        if(Identifier == 'MTD'){
            sDate = Date.newInstance(System.today().year(), System.today().month(), 1).addMonths(-1);
            eDate = Date.newInstance(System.today().year(), System.today().month(), 1).addDays(-1);
            database.executeBatch(new CustomerDashboardCalculationsBatch(sDate,eDate,'LM'));
        }
        else if(Identifier == 'LM'){
            sDate = System.today().addMonths(-3).toStartOfMonth();
            eDate = System.today().toStartOfMonth().addDays(-1);
            database.executeBatch(new CustomerDashboardCalculationsBatch(sDate,eDate,'L3M'));
        }
        else if(Identifier == 'L3M'){
            sDate = Date.newInstance(System.today().year(), System.today().month(), 1).addMonths(-12);
            eDate = Date.newInstance(System.today().year(), System.today().month(), 1).addDays(-1);
            database.executeBatch(new CustomerDashboardCalculationsBatch(sDate,eDate,'L12M'));
        }
        else if(Identifier == 'L12M'){
            sDate = System.today().month() >= 4 ? Date.newInstance(System.today().year(), 4, 1) : Date.newInstance(System.today().year() - 1, 4, 1);
            eDate = System.today().month() >= 4 ? Date.newInstance(System.today().year() + 1, 3, 31) : Date.newInstance(System.today().year(), 3, 31);
            database.executeBatch(new CustomerDashboardCalculationsBatch(sDate,eDate,'YTD'));
        }
        else if(Identifier == 'YTD'){
            sDate = Date.newInstance(System.today().year(), System.today().month(), 1).addMonths(-1);
            eDate = System.today().addMonths(-1);
            database.executeBatch(new CustomerDashboardCalculationsBatch(sDate,eDate,'LMTD'));
        }
        else if(Identifier == 'LMTD'){
            //Batch Finished
        }
    }
}