force-app/main/default/objects/CustomerDashboard__c/CustomerDashboard__c.object-meta.xml
<CustomObject>
    <label>Customer Dashboard</label>
    <nameField>
        <displayFormat>CD#{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Dashboard</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerDashboard__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Dashboard</relationshipLabel>
    <relationshipName>Customer_Dashboard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CasesClosedL12M__c.field-meta.xml
<CustomField>
    <fullName>CasesClosedL12M__c</fullName>
    <label># Cases Closed L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CasesClosedL3M__c.field-meta.xml
<CustomField>
    <fullName>CasesClosedL3M__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Cases Closed L3M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CasesClosedLM__c.field-meta.xml
<CustomField>
    <fullName>CasesClosedLM__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Cases Closed LM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CasesClosedMTD__c.field-meta.xml
<CustomField>
    <fullName>CasesClosedMTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Cases Closed MTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CasesClosedYTD__c.field-meta.xml
<CustomField>
    <fullName>CasesClosedYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Cases Closed YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CasesOpenL12M__c.field-meta.xml
<CustomField>
    <fullName>CasesOpenL12M__c</fullName>
    <label># Cases Open L12M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CasesOpenL3M__c.field-meta.xml
<CustomField>
    <fullName>CasesOpenL3M__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Cases Open L3M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CasesOpenLM__c.field-meta.xml
<CustomField>
    <fullName>CasesOpenLM__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Cases Open LM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CasesOpenMTD__c.field-meta.xml
<CustomField>
    <fullName>CasesOpenMTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Cases Open MTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/CasesOpenYTD__c.field-meta.xml
<CustomField>
    <fullName>CasesOpenYTD__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Cases Open YTD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/OpenAsOnDate__c.field-meta.xml
<CustomField>
    <fullName>OpenAsOnDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Open As On Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/X030Revenue__c.field-meta.xml
<CustomField>
    <fullName>X030Revenue__c</fullName>
    <label>0-30 Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/X181365Revenue__c.field-meta.xml
<CustomField>
    <fullName>X181365Revenue__c</fullName>
    <label>181- 365 Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/X3190Revenue__c.field-meta.xml
<CustomField>
    <fullName>X3190Revenue__c</fullName>
    <label>31-90 Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CustomerDashboard__c/fields/X91180Revenue__c.field-meta.xml
<CustomField>
    <fullName>X91180Revenue__c</fullName>
    <label>91-180 Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DashboardDataCaseToZeroBatch.cls
public class DashboardDataCaseToZeroBatch implements Database.Batchable<sObject>, Schedulable {
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT AccountName__c,OpenAsOnDate__c,CasesClosedL3M__c,CasesClosedLM__c,CasesClosedMTD__c,CasesClosedYTD__c,CasesOpenL3M__c,CasesOpenLM__c,CasesOpenMTD__c, CasesOpenYTD__c FROM CustomerDashboard__c';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<CustomerDashboard__c> scope){
        List<CustomerDashboard__c> dashboardToUpdate = new List<CustomerDashboard__c>();
        for (CustomerDashboard__c d : scope) {
            d.CasesClosedL3M__c = 0;
            d.CasesClosedLM__c = 0;
            d.CasesClosedMTD__c = 0;
            d.CasesClosedYTD__c = 0;
            d.CasesOpenL3M__c = 0;
            d.CasesOpenLM__c = 0;
            d.CasesOpenMTD__c = 0;
            d.CasesOpenYTD__c = 0;
            d.CasesClosedL12M__c = 0;
            d.CasesOpenL12M__c = 0;
            d.OpenAsOnDate__c = 0;
            d.X030Revenue__c = 0;
            d.X3190Revenue__c = 0;
            d.X91180Revenue__c = 0;
            d.X181365Revenue__c = 0;
            dashboardToUpdate.add(d);  
        }
        if(dashboardToUpdate != null && dashboardToUpdate.size() > 0){
            update dashboardToUpdate;
        }
    }
    public void finish(Database.BatchableContext BC){
        //FINISHED
        database.executeBatch(new CustomerDashboardBatchOnCase(null,true),2000);        
    }
    public void execute(SchedulableContext SC){
        database.executeBatch(new DashboardDataCaseToZeroBatch(),2000);
    }
}